### ISSUE TITLE
 Could not find a version that satisfies the requirement ipgetter

### ISSUE THREAD

**Issue by evyacik** [antonku/ncssl_api_client#7]
The requirement "ipgetter" is not available.
please advise.

Thank you :)

**Comment by antonku** [comment]
@evyacik Hi, thank you for opening the issue.
The error has been reproduced and I am planning to publish a version with the fix till the end of this week.
I will keep you posted.

**Comment by antonku** [comment]
@evyacik Hello, version (0.4) containing the fix has been published on PyPI, the api client should install now without errors. Therefore, I am closing this issue. Thanks again for your feedback!
