### ISSUE TITLE
Create PositiveSSL Multi Domain with more then 3

### ISSUE THREAD

**Issue by evyacik** [antonku/ncssl_api_client#9]
Hi,

The default amount of domain in PositiveSSL Multi Domain is 3 , is there a switch that I can specify a number of Domains I like to add?
There is an option like this in the GUI and also in the API documentation: 
https://www.namecheap.com/support/api/methods/ssl/create.aspx

SANStoADD | Number | 2 | No | Defines number of add-on domains to be purchased in addition to the default number of domains included into a multi-domain certificate.

Thank you.

**Comment by antonku** [comment]
Hi @evyacik !

Thank you for getting back, `SANStoADD` has not been supported, however to meet your requirements I have added it today, and published the new version of a package (1.0.2).

Once you upgrade the package you can issue a `create` command with new option `--sans_to_add=n`, where `n` is the number of additional SANs to purchase, for example the full command for production env can be as follows:

`ncsslapi create -t "PositiveSSL Multi Domain" --sans_to_add=3`

Don't forget to add `-sb` should you want to run in in sandbox.

Is there any questions, please let me know.

**Comment by evyacik** [comment]
Hi @antonku ,

Thank you so much , it works perfectly.
I have another question where do I insert the CSR key for SSL activation?

Thank you.

**Comment by antonku** [comment]
Hi @evyacik,

I am closing this issue, since the original request has been fulfilled. Should you have any questions, please do not hesitate to open a new issue.
